// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.component.tooltip;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class ToolTipCompComponent extends RichDeclarativeComponent {

  public ToolTipCompComponent() {
  }

  public String getMessage() {
    return (String) getAttributes().get("message");
  }

  public String getIcon() {
    return (String) getAttributes().get("icon");
  }



}
