// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.component.tooltip;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class ToolTipCompTag extends RichDeclarativeComponentTag {

  public ToolTipCompTag() {
  }

  protected String getViewId() {
    return "/com/component/tooltip/ToolTipComp.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new ToolTipCompComponent();
  }

  public void setMessage(ValueExpression message) {
    this._message = message;
  }

  public void setIcon(ValueExpression icon) {
    this._icon = icon;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_message != null)
      bean.setValueExpression(_MESSAGE_KEY, _message);
    if (_icon != null)
      bean.setValueExpression(_ICON_KEY, _icon);
  }

  public void release() {
    super.release();
    _message = null;
    _icon = null;
  }

  private ValueExpression _message;
  private ValueExpression _icon;

  private static final PropertyKey _MESSAGE_KEY = PropertyKey.createPropertyKey("message");
  private static final PropertyKey _ICON_KEY = PropertyKey.createPropertyKey("icon");

}
